name: zmk-build-and-release

on:
  push:
    paths:
      - '.github/workflows/build.yml'
      - 'boards/**'
      - 'config/**'
      - 'zephyr/**'
      - 'build.yaml'
    branches: [ "mainline" ]
  pull_request:
    paths:
      - '.github/workflows/build.yml'
      - 'boards/**'
      - 'config/**'
      - 'zephyr/**'
      - 'build.yaml'
    branches: [ "mainline" ]
  workflow_dispatch:

jobs:
  build:
    permissions:
      contents: read

    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@v0.3

  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Release artifacts
        uses: softprops/action-gh-release@v3
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: firmware.zip
